spring :
  application:
    name: blog-pjt-be
  datasource:
    url: jdbc:postgresql://localhost:5432/skeletondb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
